DROP TABLE IF EXISTS TBL_TRANSACTION;

CREATE TABLE TBL_TRANSACTION (
  transactionId INT AUTO_INCREMENT  PRIMARY KEY,
  payer VARCHAR(250) NOT NULL,
  points Numeric NOT NULL,
  timestamps  VARCHAR(250) NOT NULL
);

